services:
  coredrive-rx:
    build:
      context: https://github.com/efiten/coredrive-rx.git#master
    ports:
      - "{$RX_PORT:-8443}:80"
    volumes:
      - {$CONFIG_FILE}:/usr/share/nginx/html/config.json:ro
    restart: unless-stopped
